name: 01 - Building Blocks

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Say Hello
        run: echo "Hello, World!"
  second_job:
    runs-on: ubuntu-latest
    steps: 
      - name: Successful step
        run: |
          echo "I will succeed"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye!"